---
language: node_js
node_js:
  - "10"

sudo: false
dist: trusty

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install
  - yarn build

script:
  - yarn test