"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var emberLifecycleHooks;
(function (emberLifecycleHooks) {
    emberLifecycleHooks["INIT"] = "init";
    emberLifecycleHooks["SETUP_CONTROLLER"] = "setupController";
    emberLifecycleHooks["DID_RECIECE_ATTRS"] = "didReceiveAttrs";
    emberLifecycleHooks["WILL_RENDER"] = "willRender";
    emberLifecycleHooks["DID_INSERT_ELEMENT"] = "didInsertElement";
    emberLifecycleHooks["DID_RENDER"] = "didRender";
    emberLifecycleHooks["DID_UPDATE_ATTRS"] = "didUpdateAttrs";
    emberLifecycleHooks["WILL_UPDATE"] = "willUpdate";
    emberLifecycleHooks["WILL_DESTORY"] = "willDestroy";
    emberLifecycleHooks["WILL_DESTROY_ELEMENT"] = "willDestroyElement";
    emberLifecycleHooks["WILL_CLEAR_RENDER"] = "willClearRender";
    emberLifecycleHooks["DID_DESTROY_ELEMENT"] = "didDestroyElement";
    emberLifecycleHooks["RESET_CONTROLLER"] = "resetController";
})(emberLifecycleHooks = exports.emberLifecycleHooks || (exports.emberLifecycleHooks = {}));
var emberComponentProps;
(function (emberComponentProps) {
    emberComponentProps["CLASS_NAMES"] = "classNames";
    emberComponentProps["CLASS_NAME_BINDINGS"] = "classNameBindings";
    emberComponentProps["TAG_NAME"] = "tagName";
    emberComponentProps["ATTR_BINDINGS"] = "attributeBindings";
    emberComponentProps["LAYOUT"] = "layout";
})(emberComponentProps = exports.emberComponentProps || (exports.emberComponentProps = {}));
var emberObjectTypes;
(function (emberObjectTypes) {
    emberObjectTypes["COMPONENT"] = "Component";
    emberObjectTypes["SERVIICE"] = "Service";
})(emberObjectTypes = exports.emberObjectTypes || (exports.emberObjectTypes = {}));
var emberMultiLineObjectMethods;
(function (emberMultiLineObjectMethods) {
    emberMultiLineObjectMethods["COMPUTED"] = "computed";
    emberMultiLineObjectMethods["FILTER"] = "filter";
    emberMultiLineObjectMethods["FILTER_BY"] = "filterBy";
    emberMultiLineObjectMethods["MAP"] = "map";
    emberMultiLineObjectMethods["MAP_BY"] = "mapBy";
})(emberMultiLineObjectMethods = exports.emberMultiLineObjectMethods || (exports.emberMultiLineObjectMethods = {}));
var emberSingleLineObjectMethods;
(function (emberSingleLineObjectMethods) {
    emberSingleLineObjectMethods["OR"] = "or";
    emberSingleLineObjectMethods["AND"] = "and";
    emberSingleLineObjectMethods["NOT"] = "not";
    emberSingleLineObjectMethods["ALIAS"] = "alias";
    emberSingleLineObjectMethods["BOOL"] = "bool";
    emberSingleLineObjectMethods["COLLECT"] = "collect";
    emberSingleLineObjectMethods["EMPTY"] = "empty";
    emberSingleLineObjectMethods["EQUAL"] = "equal";
    emberSingleLineObjectMethods["GT"] = "gt";
    emberSingleLineObjectMethods["GTE"] = "gte";
    emberSingleLineObjectMethods["LT"] = "lt";
    emberSingleLineObjectMethods["LTE"] = "lte";
    emberSingleLineObjectMethods["INTERSECT"] = "intersect";
    emberSingleLineObjectMethods["MATCH"] = "max";
    emberSingleLineObjectMethods["MAX"] = "max";
    emberSingleLineObjectMethods["MIN"] = "min";
    emberSingleLineObjectMethods["NONE"] = "none";
    emberSingleLineObjectMethods["NOT_EMPTY"] = "notEmpty";
    emberSingleLineObjectMethods["ONE_WAY"] = "oneWay";
    emberSingleLineObjectMethods["READ_ONLY"] = "readOnly";
    emberSingleLineObjectMethods["READS"] = "reads";
    emberSingleLineObjectMethods["SORT"] = "sort";
    emberSingleLineObjectMethods["SUM"] = "sum";
    emberSingleLineObjectMethods["UNION"] = "union";
    emberSingleLineObjectMethods["UNION_BY"] = "unionBy";
    emberSingleLineObjectMethods["UNIQ"] = "uniq";
    emberSingleLineObjectMethods["UNIQ_BY"] = "uniqBy";
})(emberSingleLineObjectMethods = exports.emberSingleLineObjectMethods || (exports.emberSingleLineObjectMethods = {}));
//# sourceMappingURL=constants.js.map